# Generated by Django 4.0.3 on 2022-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
    ]
