# Generated by Django 3.2.9 on 2022-03-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_table_alter_seller_table'),
        ('customers', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.seller'),
        ),
    ]
