# Generated by Django 3.2.9 on 2022-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='ordered', max_length=20),
        ),
    ]
