# Generated by Django 3.2.9 on 2022-03-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_id', models.AutoField(primary_key=True, serialize=False)),
                ('dist_name', models.CharField(max_length=20)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
